name: ci-build

on:
  push:
    branches:
      - dev

jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'development'

    steps:
      - name: print-secret
        run: |-
          echo "hola github"
          echo  ${{ secrets.GCP_SERVICE_ACCOUNT }}
